In [2]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [3]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [7]:
# Yes the data type of both are different
print(type(list_), type(array_list))

<class 'list'> <class 'numpy.ndarray'>


In [8]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [9]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [15]:
array_list = np.array(object = list_, dtype = int)
# This will change all variables of array_list to integer data types 

In [13]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [17]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [23]:
print('shape =' , num_array.shape, 'size = ', num_array.size)

shape = (2, 3) size =  6


In [24]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [29]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [31]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
